name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Install Clojure Tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          lein: 2.11.2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.deps.clj
          key: deps-${{hashFiles('project.clj')}}
          restore-keys: deps-

      - name: Install dependencies
        run: lein deps

      - name: Run Tests
        run: lein test

      - name: Prepare Uberjar
        run: lein uberjar
